version: "3.3"

services:
  recipe-book-postgres:
    image: seungwonbae/recipe-book-postgres
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - net
  recipe-book-was:
    depends_on:
      - recipe-book-postgres
    image: seungwonbae/recipe-book-was
    expose:
      - "5000"
    networks:
      - net
  recipe-book-ws:
    depends_on:
      - recipe-book-was
    image: seungwonbae/recipe-book-ws
    container_name: ws
    restart: always
    ports:
      - "80:80"
    networks:
      - net
volumes:
  postgres: {}
networks:
  net:
    driver: bridge